name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Check build
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          npm install
          npm run build
          npm run lint
          cd example
          npm install
          npm run build
          npm run lint
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check build
        run: |
          yarn install
          yarn build
          yarn lint
          yarn link
          cd example
          yarn link "teckos"
          yarn install
          yarn build
          yarn lint
