name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Update binaries
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          git clone --recursive https://github.com/delude88/teckos.git
          cd teckos
          npm install
          npm run build
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-latest]
    steps:
      - name: Update binaries
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.2.app || true
          sudo apt update || true
          sudo apt install -y g++-aarch64-linux-gnu || true
          git clone --recursive https://github.com/delude88/teckos.git
          cd teckos
          npm install
          npm run build
