name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Check build
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          git clone --recursive https://github.com/delude88/teckos.git
          cd teckos
          npm install
          npm run build
          npm run lint
          cd example
          npm install
          npm run build
          npm run lint
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Check build
        run: |
          git clone --recursive https://github.com/delude88/teckos.git
          cd teckos
          npm install
          npm run build
          npm run lint
          cd example
          npm install
          npm run build
          npm run lint
